[package]
name = "automation"
version = "0.1.0"
authors = ["Bomou He <paakmau@outlook.com>"]
edition = "2018"

[dependencies]
image = "0.23"
scrap = "0.5"
tfc = "0.6"
wide = { git = "https://github.com/Lokathor/wide" }
