[package]
name = "automation"
version = "0.1.0"
authors = ["Bomou He <paakmau@outlook.com>"]
edition = "2018"

[dependencies]
image = "0.23"
scrap = "0.5"
simba = { version = "0.6", features = ["packed_simd"] }
tfc = "0.6"
